# Generated by Django 3.2.6 on 2022-08-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(default=1, upload_to='articles/%Y/%m/%d', verbose_name='article image'),
            preserve_default=False,
        ),
    ]
