# Generated by Django 3.2.5 on 2021-07-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_name',
            new_name='username',
        ),
    ]
