# Generated by Django 3.2.5 on 2021-07-29 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='status',
        ),
    ]
