# Generated by Django 3.2.5 on 2021-07-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=3),
        ),
    ]
